#!/bin/bash

###
### AWACS Device Setup Script
###
### device_kerberos
###
###
### 20250801-0100
###

log "Installing Kerberos SDR support..."

## DEPENDENCIES
sudo apt-get install -y python3-pip python3-pyqt4 pyqt4-dev-tools gfortran libatlas3-base \
libatlas-base-dev python3-dev python3-setuptools libffi6 libffi-dev python3-tk pkg-config libfreetype6-dev php7.2-cli
sudo apt-get install -y libusb-1.0-0-dev
sudo pip3 install --user numpy
sudo pip3 install --user matplotlib
sudo pip3 install --user scipy
sudo pip3 install --user cairocffi
sudo pip3 install --user pyapril
sudo pip3 install --user pyargus
sudo pip3 install --user pyqtgraph
sudo pip3 install --user peakutils
sudo pip3 install --user bottle
sudo pip3 install --user paste

# PACKAGE
cd $AWACS_SOURCE
git clone https://github.com/rtlsdrblog/rtl-sdr-kerberos
cd $AWACS_SOURCE/rtl-sdr-kerberos
mkdir build	&& cd build
cmake ../ -Wno-dev -DINSTALL_UDEV_RULES=ON
make -j4
sudo make install
sudo cp ../rtl-sdr.rules /etc/udev/rules.d/
sudo ldconfig

