#!/bin/bash

###
### AWACS Device Setup Script
###
### device_limesuite
###
###
### 20250804-0100
###

case "$1" in
    remove )
        log "Removing LimeSuite support..."
        cd $AWACS_SOURCE/LimeSuite/build-dir
        sudo make uninstall
        sudo ldconfig
        cd $AWACS_SOURCE
        rm -rf $AWACS_SOURCE/LimeSuite
        ;;
    install )
        sudo apt-get install -y swig libsqlite3-dev libi2c-dev libusb-1.0-0-dev liboctave-dev libfltk1.3-dev
        sudo apt-get install -y libwxbase3.0-0v5 freeglut3-dev
        cd $AWACS_SOURCE       
        git clone https://github.com/myriadrf/LimeSuite.git
        cd LimeSuite
        git checkout stable
        mkdir build-dir && cd build-dir
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig
        ;;
    * )
        error "Unknown action on device_limesuite: $1"
        ;;
esac