#!/bin/bash

###
### AWACS Device Setup Script
###
### device_sdrplayold_run
###
###
### 20250802-2300
###


#
# Restart SDRplay
#

sudo systemctl stop sdrplay
sudo pkill sdrplay_apiService
#sudo rm -f /dev/shm/Glbl\\sdrSrv*
sudo systemctl start sdrplay