#!/bin/bash

###
### AWACS Device Setup Script
###
### device_bladerf
###
###
### 20250801-0100
###

log "Installing bladeRF support..."

## DEPENDENCIES
sudo apt-get install -y python3-six python3-mako python3-lxml python3-lxml 

## PACKAGE 
cd $AWACS_SOURCE
git clone https://github.com/Nuand/bladeRF.git
cd bladeRF
mkdir build && cd build
cmake .. -Wno-dev
make -j4
sudo make install
sudo ldconfig
